# Generated by Django 5.2.1 on 2025-06-04 16:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_final', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Quarto', models.IntegerField()),
                ('qtd_Hospedes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Premium', 'Premium'), ('Plus', 'Plus')], max_length=20)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='quarto/')),
                ('hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.hospede')),
            ],
        ),
    ]
