# Generated by Django 5.2.2 on 2025-06-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hospede_quarto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='hospede',
        ),
        migrations.AddField(
            model_name='hospede',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.quarto'),
        ),
    ]
