# Generated by Django 4.2.23 on 2025-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_remove_quarto_hospede_hospede_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
