# Generated by Django 4.2.23 on 2025-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_homepage_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='descricao',
            field=models.TextField(max_length=800),
        ),
    ]
